version: '3.8'

services:
  project_testrepo_api:
    build:
      context: ../../api
      dockerfile: dockerfile.package

    container_name: project_testrepo_api
    restart: always

    ports:
      - 80:5000

    networks:
      - project_testrepo

    depends_on:
      - project_testrepo_api_db

  project_testrepo_db:
    image: mysql:8.0
    
    container_name: project_testrepo_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: project_testrepo_db

networks:
  project_testrepo:
