version: '3.8'

services:
  project_testrepo_api:
    build:
      context: ../../api
      dockerfile: dockerfile.package

    container_name: project_testrepo_api
    restart: always

    ports:
      - 8000:8000
