FROM python:3.12.4-alpine

RUN apk update &&\
    apk upgrade

RUN apk add uvicorn &&\
    pip3 install "fastapi[standard]" "uvicorn[standard]"

RUN mkdir /app
WORKDIR /app

COPY . .

CMD ["python3", "main.py"]